config/routes.rb
Rails.application.routes.draw do

  namespace :backend do
    devise_for :admins, controllers: {
      registrations: 'backend/registrations',
      sessions: 'backend/sessions',
      passwords: 'backend/passwords',
      confirmations: 'backend/confirmations'
    }
    resources :items
  end

  devise_for :users
  get 'home/index'
  root to: "home#index"

  namespace :api, default: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [:create]
      resources :items, only: [:index]
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base

  protect_from_forgery with: :null_session

  include ErrorsConcern
  include JwtAuthConcern

  layout 'api.v1.json.jbuilder'

end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < Api::V1::BaseController

  def index
    @items = Item.all
    @meta = { items_count: @items.count }
  end

end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < ActionController::Base
  
  protect_from_forgery with: :null_session
  include ErrorsConcern
  layout 'api.v1.json.jbuilder'

  def create
    @user = User.find_by(email: user_params["email"])
    if @user && @user.valid_password?(user_params["password"])
      @jwt = JsonWebToken.encode(user_id: @user.id)
    else
      render_error(code: 404, message: "Invalid Credentials", error_fields: {}) && return
    end
  end

  private
  def user_params
    params.permit(:email, :password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController

end

app/controllers/backend/items_controller.rb
class Backend::ItemsController < Backend::BaseController
  before_action :authenticate_backend_admin!
  before_action :current_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to backend_item_path(@item)
    else
      @errors = @item.errors
      render 'new'
    end
  end

  def edit
  end

  def update
    if @item.update_attributes(item_params)
      redirect_to backend_items_path
    else
      @errors = @item.errors
      render "edit"
    end
  end

  def show
  end

  def destroy
    #binding.pry
    if @item.destroy
      redirect_to backend_items_path
    else

    end
  end


  private
  def current_item
    @item = Item.find params.require(:id)
  end

  def item_params
    params.require(:item).permit(:name, :price)
  end

end

app/controllers/backend/registrations_controller.rb
class Backend::RegistrationsController < Devise::RegistrationsController
  # layout "admin"
end

app/controllers/backend/sessions_controller.rb
class Backend::SessionsController < Devise::SessionsController
  # layout "admin"

  def create
    super
  end

  def new
    #binding.pry
    #self.resource = resource_class.new(sign_in_params)
    #store_location_for(resource, params[:redirect_to])
    super
  end

  def after_sign_in_path_for(resource)
    #sign_in_url = new_user_session_url
    #if request.referer == sign_in_url
    #  super
    #else
    #  stored_location_for(resource) || request.referer || root_path
    #end
    backend_items_path
  end

end

app/controllers/concerns/errors_concern.rb
module ErrorsConcern
  extend ActiveSupport::Concern

  included do
    def render_error(json_error)
      @error = json_error
      render 'api/v1/empty.json', status: json_error[:code]
    end
  end
end

app/controllers/concerns/jwt_auth_concern.rb
module JwtAuthConcern
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_token!

    def c_user
      return nil unless token && decoded_token
      User.find(decoded_token["user_id"])
    end
    alias_method :current_user, :c_user

    protected
    def authenticate_token!
      if c_user
        sign_in(c_user, store: false)
      else
        sign_out(c_user)
        render_error(code: 404, message: "Invalid JWT Token", error_fields: {}) && return
      end
    end

    private
    def token
      request.env.fetch("HTTP_AUTH_TOKEN") || nil
    end

    def decoded_token
      render_error(code: 404, message: "Invalid JWT Token", error_fields: {}) && return unless token
      JsonWebToken.decode(token)
    end

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/backend/_header.html.slim
nav.navbar.navbar-default
  .navbar-right.top-nav
    - if backend_admin_signed_in?
      = link_to "logout", destroy_backend_admin_session_path, class: "btn btn-danger"

app/views/backend/_layout.html.slim
= render partial: 'backend/header'
= yield

app/views/backend/items/_form.html.slim
ul
  li
    div.input-group
      span.input-group-addon= "Name"
      = f.text_field :name, class: "form-control"
  li
    div.input-group
      span.input-group-addon= "Price"
      = f.number_field :price, class: "form-control"

app/views/backend/items/edit.html.slim
hr
section.text-center
  h3= "Edit Item"
  = form_for @item, url: backend_item_path(@item) do |f|
    = render "form", f: f
    li= f.submit "Update Item", class: "btn"

app/views/backend/items/index.html.slim
= render layout: "backend/layout" do
  hr
  section.text-center
    h3="Items List"
    = link_to "Create New Item", new_backend_item_path, class: "btn btn-warning"
    ul
      - @items.each do |item|
        .row
          .col-md-6
            li= item.name
            li= item.price
          .col-md-6
            ul
              li= link_to "show", backend_item_path(item), class: "btn btn-success"
              li= link_to "edit", edit_backend_item_path(item), class: "btn btn-info"
              li= button_to 'Destroy', {action: :destroy, id: item.id},  onclick: 'return confirm("Are you sure?")', method: :delete, class: "btn btn-danger"

        hr

app/views/backend/items/new.html.slim
hr
section.text-center
  h3= "Create New Item"
  = form_for @item, url: backend_items_path do |f|
    = render "form", f: f
    li= f.submit "Create Item", class: "btn"

app/views/backend/items/show.html.slim
hr
h3="Item Show"
ul
  li= @item.name
  li= @item.price

app/views/home/index.html.erb
<hr/>
<section class="text-center">
  <%= link_to 'Admin Login', new_backend_admin_session_path, class: 'btn btn-info ' %>
</section>

<%= javascript_pack_tag 'hello_react' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBootstrap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application' %>
    <%#= stylesheet_pack_tag 'application' %>
    <%#= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </head>

  <body>
    <section class="container-fluid">
      <%= yield %>
    </section>
  </body>
</html>